apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "redis.fullname" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  {{- if not .Values.redis.autoscaling.enabled }}
  replicas: {{ .Values.redis.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "redis.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.redis.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "redis.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.redis.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "redis.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.redis.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.redis.securityContext | nindent 12 }}
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          {{- if $.Values.redis.environments }}
          env:
          {{- range $.Values.redis.environments }}
            - name: {{ .name | quote }}
              value: {{ .value | quote }}
          {{- end }}
          {{- end }}
          {{- if $.Values.redis.livenessProbe.enabled }}
          livenessProbe:
            {{- if $.Values.redis.livenessProbe.exec.command }}
            exec:
              command:
                {{- range $.Values.redis.livenessProbe.exec.command }}
                - {{ . | quote }}
                {{- end }}
            {{- end }}
            initialDelaySeconds: {{ $.Values.redis.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ $.Values.redis.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ $.Values.redis.livenessProbe.timeoutSeconds }}
            successThreshold: {{ $.Values.redis.livenessProbe.successThreshold }}
            failureThreshold: {{ $.Values.redis.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if $.Values.redis.readinessProbe.enabled }}
          readinessProbe:
            {{- if $.Values.redis.livenessProbe.exec.command }}
            exec:
              command:
                {{- range $.Values.redis.livenessProbe.exec.command }}
                - {{ . | quote }}
                {{- end }}
            {{- end }} 
            initialDelaySeconds: {{ $.Values.redis.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ $.Values.redis.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ $.Values.redis.readinessProbe.timeoutSeconds }}
            successThreshold: {{ $.Values.redis.readinessProbe.successThreshold }}
            failureThreshold: {{ $.Values.redis.readinessProbe.failureThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
      {{- with .Values.redis.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.redis.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.redis.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
