{{- if .Values.golang.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "golang-restapi.serviceAccountName" . }}
  labels:
    {{- include "golang-restapi.labels" . | nindent 4 }}
  {{- with .Values.golang.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
{{- if .Values.redis.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "redis.serviceAccountName" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
  {{- with .Values.redis.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
