apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongo.fullname" . }}
  labels:
    {{- include "mongo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mongo.service.type }}
  ports:
    - port: {{ .Values.mongo.service.port }}
      targetPort: {{ .Values.mongo.service.port }}
      protocol: TCP
      name: mongodb
  selector:
    {{- include "mongo.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongo.fullname" . }}-headless
  labels:
    {{- include "mongo.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.mongo.service.port }}
      targetPort: {{ .Values.mongo.service.port }}
      protocol: TCP
      name: mongodb
  selector:
    {{- include "mongo.selectorLabels" . | nindent 4 }}
