apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mongo.fullname" . }}
  labels:
    {{- include "mongo.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "mongo.fullname" . }}-headless
  replicas: {{ .Values.mongo.replicaCount}}
  selector:
    matchLabels:
      {{- include "mongo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "metrics"
      labels:
        {{- include "mongo.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "mongo.fullname" . }}
          image: "{{ .Values.mongo.image.repository }}:{{ .Values.mongo.image.tag | default .Chart.AppVersion }}"
          securityContext:
            {{- toYaml .Values.mongo.securityContext | nindent 12 }}
          ports:
            - containerPort: 27017
              name: mongodb
          imagePullPolicy: {{ .Values.mongo.image.pullPolicy }}
          resources:
            {{- toYaml .Values.mongo.resources | nindent 12 }}
          {{- if $.Values.mongo.environments }}
          env:
          {{- range $.Values.mongo.environments }}
            - name: {{ .name | quote }}
              value: {{ .value | quote }}
          {{- end }}
          {{- end }}
      {{- with .Values.mongo.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mongo.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mongo.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}         